source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, '8.0'
target 'gushiwendaquan' do
pod 'Mantle', '~> 1.5'
pod 'Masonry', '~> 0.5.3'
pod 'AFNetworking', '~> 2.3.1'
pod 'CocoaSecurity', '~> 1.2.4'
pod 'FMDB', '~> 2.3'
pod 'NSString-UrlEncode', '~> 1.1.0'
pod 'CocoaLumberjack', '~> 1.9.2'
pod 'SVProgressHUD'
pod 'JDStatusBarNotification'
pod 'SDWebImage'
pod 'JSONModel'
pod 'MJExtension'
pod 'Toast'
pod 'RTLabel'
pod 'JSBadgeView'
pod 'MBProgressHUD'
pod 'RegexKitLite'
pod 'pop', '~> 1.0'
pod 'NJKWebViewProgress'
pod 'Aspects'
pod 'AXPracticalHUD'
end
